# Appendix 1 - Additional Details and Code Snippets


## Installing software via the command-line

### Installing or using Homebrew

Homebrew is an open-sources package manager for macOS. Using it makes
installing other macOS software via the command-line fairly easy.

To see if Homebrew is installed on your mac, open a terminal window and
type

> \$brew

If Homebrew is installed, your terminal window will open the Homebrew
manual (Figure 18)

![Text Description automatically
generated](media/image23.png){width="3.4672123797025374in"
height="2.8882327209098864in"}

[]{#_Ref71109386 .anchor}Figure 18. Checking to see if Homebrew is
installed.

If Homebrew is not installed, you will receive an error message.

To install Homebrew on a mac, follow the instructions
[here](https://www.igeeksblog.com/how-to-install-homebrew-on-mac/).

The quick version:

Install Homebrew first. Copy the following line at the command-prompt in
your terminal window to do so:

/usr/bin/ruby -e \"\$(curl -fsSL
<https://raw.githubusercontent.com/Homebrew/install/master/install>)\"

You will be prompted to type in a password. Type in the same password
you use to log on to the computer. When you type in the password,
nothing will appear in the command line but the computer will know after
you hit enter. The computer will install Homebrew, which may take 20 or
so minutes.

### Installing imageMagick on a mac 

First, determine if imageMagick is installed on your computer. Open a
terminal window and type:

\$magick

If the manual pages open, then imageMagick is installed. If not, you
will need to install it.

To install imagemagick, type the following at the command prompt:

\$brew install imagemagick

You may need to enter your password to continue, and it may take several
minutes to install.

### Installing exifTool on a mac

First, determine if exifTool is installed on your computer. Open a
terminal wondw and type:

\$exiftool

If the manual pages open, then exifTool is installed. If not, you will
need to install it.

To install exifTool using Homebrew, type the following at the command
prompt:

\$brew install exiftool

You may need to enter your password to continue, and it may take several
minutes to install.

## Using exifTool to write metadata csv from [within]{.ul} image directory

Make sure you are in the directory that has all of the images. For
example, imagine you are in a folder called "Card 4".

You can specify that an action happen on the same directory you are in
by using the '.' Notation.

Thus, to export the .csv, you would type:

\$exiftool -common -csv . \> correctfilename.csv

This code tells the computer to "Open exiftool, select the "common"
(rather than all) the exif data, and make a csv using all of the images
in the directory you are currently in (the '.') and save it to a file
called correctfilename.csv in the same directory.

[^1]: I mean NEVER, EVER, EVER. Got it?

[^2]: Never, ever ever! Not even AFTER hell freezes over!

[^3]: You know the drill: Never as in NOT EVER!


