# Add any additional data to the manifest file

This required step is done using Excel to add any added metadata to the manifest that you would like to be associated with the images. This step must be done before pushing images to the Zooniverse. Talk with Erika about whether you will be adding metadata to the manifest.

## Manifest file conventions

The first four columns of the manifest file are predetermined by our R code and indicate

You can add columns of data to the manifest to keep information associated with events. For example, you might want to add a column for the forest name or columns with the latitude and longitude of the camera locations. There may be information that you'd like to keep hidden from the zooniverse volunteers who classify images for us. 

- Any column field whose name begins with `!` will not be accessible to volunteers in the classification interface but will be available in the talk interface after classification.

- Any column field whose name begins with `#` or `//` will never be shown to zooniverse volunteers, ever. 

## Copy the manifest file (again) to the correct location on the external hard drive.

We store a copy of the manifest file on the t:drive because it is automatically backed up. However, to upload the manifest to Zooniverse, it needs to be located in the folder of images we intend to upload. For that reason, copy the manifest file you just created on the t:drive and navigate to the folder of images you plan to upload, located on the external hard drive. Paste the manifest file into the folder of images. The correct folder is usually called "All_" something (e.g. "All_R1", "All_AvS")

**The only things in the folder with images to upload should be the actual image files and the manifest.**

## Summary
At the end of this step, you will have a single folder including processed image files and the zooniverse manifest file ready for upload to the zooniverse platform.