# Use ExifTool to repair incorrect time stamps on images

Sometimes a camera malfunctions and resets the time stamp on each image to the incorrect date. Other times the camera trapper overlooks setting the date and time correctly in the camera when it is deployed. In either case, we need to repair the date and time on the images so that when we assign them to events, they occur in the proper order.

For more information about the following steps, consult [this webpage](https://www.labnol.org/software/change-date-of-pictures/28336/) on line.

We will again be using terminal and the command-line interface. 

## Finding the time difference
Oftentimes, when game cameras malfunction, they set the date to the original date/time associated with their manufacture and software build (e.g. January 1, 2020). It can be clunky to find out the exact time/date difference between the actual photos and the timestamp on the photos created by the camera. This website can be helpful!

[Time and Date](https://www.timeanddate.com/date/durationresult.html?m1=1&d1=1&y1=2020&m2=09&d2=04&y2=2024&h1=1&i1=20&s1=&h2=14&i2=05&s2=)

## Code to add one month to the Date / Time Original exif field:

From within the directory in which you plan to fix the dates/times, run the following line of code. In this example, you are adding one month to the time stamp and are doing it to all of the image files in the directory.

`exiftool "-DateTimeOriginal+=0:1:0 0:0:0" *.JPG`

## Example 2 - Changing just the time but not the date

Sometimes we accidentally set our cameras as pm when we should set the time as am, which means we need to subtract (or add, depending on the specifics) 12 hours to the time for each photo. Here is the code that will subtract 12 hours from the date/time on each image in a directory.

`exiftool "-DateTimeOriginal-=0:0:0 12:0:0" *.JPG`
## Write csv from the parent directory

You should create the csv by specifying the folder containing the images
for which you want the data, without being in that folder. From the
folder with the images, use cd .. to navigate to the parent folder that
contains the image folder.

For the purpose of this example, assume that all of the images are in a
folder called *Card_4*

If you haven't already done so, navigate in the terminal to the parent directory that holds Card_4. Then write the following in the command line:

$ exiftool --common -csv Card_4 > correctfilename.csv

This code tells the computer to "Open exiftool, select the "common"
(rather than all) the exif data, and make a csv using all of the images
in the Card_4 folder and save it to a file called
correctfilename.csv in the parent directory. 

Your exiftool command will do several things:

1.  It will open the directory with the images
2.  It will examine and extract the common pieces of exif information from each image and store them in a csv file and

3.  It will save the csv to the parent, rather than the child directory.

## Assign the csv a correct file name

In the code above, we used *correctfilename.csv* as a placeholder file
name for the csv file that we were making with exifTool. In reality, we
want to use meaningful file names whenever we create files. Keep in mind
that the file is going to be moved, stored, and opened again, perhaps
years later. We need to know what it is! Thus we will use a meaningful
file naming convention.

We'd like to know, just from the file name, several things:

1.  What the file contains (exif data)

2.  What set of images the file is for (timeframe and round, if
    relevant). Recall that the camera and sd card names are already
    embedded in the image names, so we don't need that info in the file
    name.

So for data from the fall 2021 camera trapping season, we would use the
following components in the file name:

-   "exif" to tell us that it contains exif data

-   "2021" to tell us the year it is from

-   "R1" or "R2" etc. to tell us the round of deployments

-   The name of the folder containing the images it is referencing.

Thus, the line of code we would use to create the exif metadata file
from the parent folder would be:

`$ exiftool --common -csv Card_4  exif_2021_R1.csv`

## Moving the file to the correct location

The last step in all of this image processing is to copy the exif
metadata file you just created to the main NoCoWild Data subfolder.

Navigate to t://Bart_s04/Research_group/NoCoWild/Data/exif_metadata and
save a copy of the file you just created there.

## Summary
By the end of this step, you will have created a .csv file in the parent directory to the folder containing all of the images you are preparing. You will have saved a copy of that .csv file in the designated location the t:// drive.
